### ISSUE TITLE
Move this repo to the osm-americana organization

### ISSUE THREAD

**Issue by ZeLonewolf** [osm-americana/openstreetmap-americana#1121]
I intend to move this repo into the github/osm-americana organization. In my experience, this is smooth and links follow.  I'm not sure about github.io links, which may need changing.

Is there anything that would prevent us from making that move?

Identified pre- and post-move tasks
- [x] Install americanamap.org domain name
- [x] Update taginfo JSON file location taginfo/taginfo-projects#193
- [x] Move webfonts repo to webfont.americanamap.org #1135 
- [x] Actually transfer the repo
- [x] Update americanamap.org CNAME entry for www to point to new location
- [x] Update links with https://raw.githubusercontent.com/ZeLonewolf/openstreetmap-americana/, e.g. taginfo images #1144 
- [x] Update taginfo [project](https://taginfo.openstreetmap.org/projects/osm_americana#overview) URL with new GitHub location #1144 
- [x] Update github.com links in the repo source code after the move #1144 
- [x] Update links/annotations on Americana YouTube videos of presentations and talks
- [x] Publish npm update with new links #1146
- [x] Update Slack github channel with new subscription

**Comment by jleedev** [comment]
That's correct:

> However, we don't redirect GitHub Pages associated with the repository.

https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by 1ec5** [comment]
Most people are using OSM Americana through the GitHub Pages deployment. In the past, I’ve seen that, if you rename a repository, the associated deployment moves to the new location _without_ a redirect, breaking bookmarks and links with an unhelpful 404.

If this is still the case with the GitHub Actions workflow we have, then we’ll need to recreate a stub repo at the original location that contains an HTML redirect page. Alternatively, the osm-american org can fork this repository, then the upstream can replace the deployed landing page with a redirect. Unfortunately, either way, I don’t know of a way to redirect non-HTML files in Jekyll/GitHub Pages. That could be disruptive for anyone who’s consuming a JSON file directly.

**Comment by ZeLonewolf** [comment]
From cursory googling, it appears that if I create a stub repo with HTML redirect pages to fix github.io forwarding, that will remove the forwarding link on the github.com side.

**Comment by ZeLonewolf** [comment]
Would it be workable to use DNS with a short TTL via the steps [here](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site)? Then we can get everyone to switch to a new domain and then re-point the domain.  There will be a short gap for DNS propagation but hopefully TTL can solve that for us.

**Comment by ZeLonewolf** [comment]
Taginfo [project](https://taginfo.openstreetmap.org/projects/osm_americana#overview) is now showing the update info.

**Comment by quincylvania** [comment]
> Update links/annotations on Americana YouTube videos of presentations and talks

I did this for all the OSM US presentations. Annotations are apparently gone from YouTube but I added "cards" that link out to americanamap.org that appear on the video when the site is mentioned.

**Comment by ZeLonewolf** [comment]
Complete!
